units:
  wraps:
  - name: PrometheusxFlaskxExporterGitHubReleaseNotesWrap
    type: wrap.GHReleaseNotes
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: prometheus-flask-exporter
    run:
      release_notes:
        organization: rycus86
        repository: prometheus_flask_exporter
