units:
  boots:
  - name: QuaySecurityTimestampInfoBoot
    type: boot
    metadata:
      datetime: "2022-12-18T00:00:38.153121"
    should_include:
      adviser_pipeline: true
      runtime_environments:
        base_images:
          not: [null]
    run:
      stack_info:
      - type: INFO
        message: >-
          Using security information for predictable stacks based on Quay
          scanners for quay.io/organization/thoth-station as of '2022-12-18T00:00:38.153121'
        link: https://www.projectquay.io/
        metadata:
          - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
            prescriptions_version: 0.8.0
